"""The Repository Leader lane, end to end against its own two adapters (PR 8).

Every document here comes from ``contracts/leader-actions/v1/fixtures``. Nothing
in this file hand-rolls a wire shape, because a test that spelled the contract
out a second time would go on passing after the freeze moved — which is the one
thing a consumer suite must not do. Where a shape is asserted it is asserted
with ``validate_document``, the same walker the wave-0 contract test uses, so a
schema construct neither side understands fails loudly in both suites at once.

Four things are checked and they need four different kinds of double:

* **The wire models** against the frozen fixtures, both directions.
* **The full lane** against ``InMemoryLeaderActionPort``, which really runs the
  phase machine. Planning to receipt to review to verdict, plus the refusals and
  the replays — all the claims the lane rests on, none of them faked.
* **The HTTP adapter** against the production FastAPI route, in process. Only
  ``GET`` exists on the server today (PR 7 lands the two writes), so that is
  what is covered: a 200 that parses, and the three refusals that must arrive as
  typed exceptions carrying the frozen code.
* **The coordination session** against a fake driver, where the load-bearing
  assertions are negative: no repository reaches the prompt or the process, a
  malformed answer is refused rather than repaired, and a model that writes its
  own provenance is turned away.

The leader notice fixture is generated by running RepoMesh's own leader-mode
assignment, not by copying its wording here. That is the only way the recogniser
stays honest: if the server rewords the notice, this test changes with it, and
if the server moves the *route*, this test fails — which is correct, because the
route is what the recogniser reads.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from uuid import UUID, uuid4

import httpx
import pytest
from api.test_leader_actions import LEADER_TASK_ID, LEADER_TOKEN, WORKER_TOKEN, build_client
from contracts.test_leader_actions_v1_contract import validate_document
from task_orchestration.test_leader_mode_assignment import start_leader_mode_round

from agent_bridge.test_coding_session import _FakeDriver, _make_session
from repomesh.modules.collaboration.contracts import CollaborationMessageKind
from repomesh_agent_bridge.adapters.leader_actions import (
    ASSIGNMENT_PATH,
    PLAN_PATH,
    REVIEW_PATH,
    RepoMeshLeaderActionAdapter,
)
from repomesh_agent_bridge.adapters.leader_session import LeaderCoordinationSession
from repomesh_agent_bridge.adapters.memory import InMemoryLeaderActionPort
from repomesh_agent_bridge.contracts import (
    LEADER_ACTION_ERROR_CODES,
    LeaderDocumentInvalid,
    PlanReceipt,
    RepositoryAssignmentPackage,
    RepositoryPlanDecision,
    RepositoryReviewDecision,
    ReviewEvidence,
    ReviewReceipt,
    read_leader_action_error,
)
from repomesh_agent_bridge.leader_lane import (
    parse_leader_assignment_notice,
    render_fact_package,
    render_plan_instructions,
    render_review_instructions,
)
from repomesh_agent_bridge.ports import LeaderActionRefused, LeaderActionUnavailable
from repomesh_runner.drivers.base import DriverResult, DriverResultStatus

CONTRACT = Path(__file__).parents[2] / "contracts" / "leader-actions" / "v1"
FIXTURES = CONTRACT / "fixtures"


def load(name: str) -> Any:
    return json.loads((FIXTURES / name).read_text(encoding="utf-8"))


def schema(name: str) -> Any:
    return json.loads((CONTRACT / name).read_text(encoding="utf-8"))


def planning_package() -> RepositoryAssignmentPackage:
    return RepositoryAssignmentPackage.from_wire(load("assignment-package.planning.json"))


def review_evidence() -> ReviewEvidence:
    package = RepositoryAssignmentPackage.from_wire(load("assignment-package.review-due.json"))
    assert package.review_evidence is not None
    return package.review_evidence


def valid_plan() -> RepositoryPlanDecision:
    return RepositoryPlanDecision.from_wire(load("plan-decision.valid.json"))


def approve() -> RepositoryReviewDecision:
    return RepositoryReviewDecision.from_wire(load("review-decision.approve.json"))


def rework() -> RepositoryReviewDecision:
    return RepositoryReviewDecision.from_wire(load("review-decision.request-rework.json"))


def port() -> InMemoryLeaderActionPort:
    return InMemoryLeaderActionPort(planning_package(), review_evidence=review_evidence())


# ---------------------------------------------------------------------------
# The wire models, against the freeze
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("fixture_name", "schema_name", "model"),
    [
        (
            "assignment-package.planning.json",
            "repository-assignment-package.schema.json",
            RepositoryAssignmentPackage,
        ),
        (
            "assignment-package.review-due.json",
            "repository-assignment-package.schema.json",
            RepositoryAssignmentPackage,
        ),
        (
            "plan-decision.valid.json",
            "repository-plan-decision.schema.json",
            RepositoryPlanDecision,
        ),
        (
            "review-decision.approve.json",
            "repository-review-decision.schema.json",
            RepositoryReviewDecision,
        ),
        (
            "review-decision.request-rework.json",
            "repository-review-decision.schema.json",
            RepositoryReviewDecision,
        ),
        ("plan-receipt.json", "plan-receipt.schema.json", PlanReceipt),
        ("review-receipt.approve.json", "review-receipt.schema.json", ReviewReceipt),
    ],
)
def test_every_fixture_round_trips_through_the_bridge_model(
    fixture_name: str, schema_name: str, model: Any
) -> None:
    """Read the frozen document, write it back, and get the same bytes.

    Round trip rather than "it parses", because a reader that silently dropped a
    field would pass the weaker test and lose data on the way out — and one of
    these documents is the leader's own product, which the server persists
    verbatim.
    """

    document = load(fixture_name)
    written = model.from_wire(document).to_wire()
    assert written == document
    validate_document(schema(schema_name), written)


def test_the_planning_package_carries_no_evidence_and_review_due_does() -> None:
    """Frozen invariant 1, enforced by the model rather than trusted."""

    assert planning_package().review_evidence is None
    assert review_evidence().review_revision == 1


def test_a_package_whose_phase_and_evidence_disagree_is_refused() -> None:
    document = load("assignment-package.planning.json")
    document["phase"] = "review_due"
    with pytest.raises(LeaderDocumentInvalid, match="review evidence"):
        RepositoryAssignmentPackage.from_wire(document)


def test_a_plan_with_a_cycle_is_refused_by_the_bridge_not_by_the_server() -> None:
    """Adjudication B2-2: the Bridge validates before it posts.

    The fixture is schema-valid on purpose — its defect is the graph, not the
    shape — so this is the check that catches it, and catching it here is what
    keeps a leader from learning about its own cycle from a 409.
    """

    with pytest.raises(LeaderDocumentInvalid, match="acyclic"):
        RepositoryPlanDecision.from_wire(load("plan-decision.invalid-dag-cycle.json"))


def test_a_plan_whose_nodes_and_tasks_disagree_is_refused() -> None:
    document = load("plan-decision.valid.json")
    document["taskDag"]["nodes"].append({"nodeId": "orphan"})
    with pytest.raises(LeaderDocumentInvalid, match="one-to-one"):
        RepositoryPlanDecision.from_wire(document)


def test_request_rework_without_an_instruction_is_refused() -> None:
    document = load("review-decision.request-rework.json")
    del document["findings"][0]["reworkInstruction"]
    with pytest.raises(LeaderDocumentInvalid, match="reworkInstruction"):
        RepositoryReviewDecision.from_wire(document)


def test_a_decision_without_leader_session_provenance_is_refused() -> None:
    document = load("plan-decision.valid.json")
    document["provenance"]["source"] = "server"
    with pytest.raises(LeaderDocumentInvalid, match="source"):
        RepositoryPlanDecision.from_wire(document)


def test_the_bridge_and_the_freeze_agree_on_the_whole_error_vocabulary() -> None:
    """The consumer's copy of the code enum, held against the contract's own.

    The Bridge carries an unrecognised code through rather than raising on it,
    which is the right behaviour and also the reason this test has to exist: a
    build that had quietly fallen behind the freeze would go on working and
    nothing would say so.
    """

    enum = schema("structured-error.schema.json")["properties"]["detail"]["properties"]["code"][
        "enum"
    ]
    assert list(LEADER_ACTION_ERROR_CODES) == enum
    matrix: dict[str, list[str]] = load("error-matrix.json")
    assert sorted(LEADER_ACTION_ERROR_CODES) == sorted(
        code for codes in matrix.values() for code in codes
    )


def test_an_unrecognised_code_is_carried_through_rather_than_crashed_on() -> None:
    """Drift is when the message matters most, so it is not when to raise."""

    code, message = read_leader_action_error(
        {"detail": {"code": "a_code_from_a_later_freeze", "message": "RepoMesh said no"}}
    )
    assert code == "a_code_from_a_later_freeze"
    assert message == "RepoMesh said no"


@pytest.mark.parametrize(
    ("fixture_name", "expected"),
    [
        ("plan-decision.invalid-assignee.json", "roster"),
        ("plan-decision.valid.json", None),
    ],
)
def test_the_envelope_clamp_is_evaluated_against_the_package(
    fixture_name: str, expected: str | None
) -> None:
    """Frozen invariant 4, checked where both halves are in hand."""

    reason = planning_package().refuse_plan(RepositoryPlanDecision.from_wire(load(fixture_name)))
    if expected is None:
        assert reason is None
    else:
        assert reason is not None and expected in reason


def test_a_plan_that_drops_an_envelope_test_command_is_refused() -> None:
    document = load("plan-decision.valid.json")
    document["workerTasks"][0]["tests"] = []
    reason = planning_package().refuse_plan(RepositoryPlanDecision.from_wire(document))
    assert reason is not None and "test command" in reason


def test_a_plan_that_reaches_outside_the_envelope_roots_is_refused() -> None:
    document = load("plan-decision.valid.json")
    document["workerTasks"][0]["allowedPaths"] = ["src/billing/"]
    reason = planning_package().refuse_plan(RepositoryPlanDecision.from_wire(document))
    assert reason is not None and "outside the safety envelope" in reason


# ---------------------------------------------------------------------------
# Body B: the notice RepoMesh actually sends
# ---------------------------------------------------------------------------


async def leader_notice() -> tuple[str, UUID]:
    """The real notice body, produced by RepoMesh's own leader-mode assignment.

    Generated rather than transcribed. A copy here would keep passing after the
    server changed the message, which would mean the recogniser had quietly
    stopped recognising anything real.
    """

    environment = await start_leader_mode_round()
    decisions = [
        command
        for command, _ in environment.collaboration.sent
        if command.kind is CollaborationMessageKind.DECISION
    ]
    assert len(decisions) == 1, "leader-mode parking sends exactly one decision notice"
    return decisions[0].body, decisions[0].task_id


async def test_the_real_leader_notice_is_recognised_and_names_its_task() -> None:
    body, leader_task_id = await leader_notice()
    assert parse_leader_assignment_notice(body) == leader_task_id


async def test_the_real_leader_notice_carries_no_secret_and_no_path() -> None:
    """A sanity check on the input, not on the parser.

    If the notice ever started carrying a workspace path, the leader lane would
    be one careless prompt away from breaking D-8 — so the shape of the message
    the lane reads is worth pinning here rather than discovering later.
    """

    body, _ = await leader_notice()
    assert "\\" not in body
    assert "Bearer" not in body


@pytest.mark.parametrize(
    "body",
    [
        "",
        "please plan the pricing work",
        # A leader task named without the plan route: a mention, not a dispatch.
        f"see /api/v1/agent-actions/leader/assignments/{uuid4()} when you get a chance",
        # The review notice's route, which is a different event entirely.
        f"POST /api/v1/agent-actions/leader/assignments/{uuid4()}/review",
    ],
)
def test_a_message_that_is_not_the_notice_wakes_nothing(body: str) -> None:
    assert parse_leader_assignment_notice(body) is None


def test_a_notice_naming_two_leader_tasks_is_declined_rather_than_guessed() -> None:
    first, second = uuid4(), uuid4()
    body = (
        f"  GET  /api/v1/agent-actions/leader/assignments/{first}\n"
        f"  POST /api/v1/agent-actions/leader/assignments/{second}/plan\n"
    )
    assert parse_leader_assignment_notice(body) is None


# ---------------------------------------------------------------------------
# The whole lane, against the in-memory port
# ---------------------------------------------------------------------------


async def test_the_planning_half_runs_from_notice_to_receipt() -> None:
    lane = port()

    package = await lane.fetch_assignment(LEADER_TASK_ID_OF_FIXTURE)
    assert package.phase == "planning"
    assert package.review_evidence is None

    receipt = await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())

    assert receipt.plan_revision == 1
    # The receipt names the tasks the evidence later reports on: one scenario,
    # one identity, exactly as the frozen fixtures spell it.
    assert receipt.to_wire() == load("plan-receipt.json")
    assert lane.phase == "executing"


async def test_the_review_half_runs_from_evidence_to_terminal_verdict() -> None:
    lane = port()
    await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    lane.worker_tasks_finished()

    package = await lane.fetch_assignment(LEADER_TASK_ID_OF_FIXTURE)
    assert package.phase == "review_due"
    assert package.review_evidence is not None

    receipt = await lane.submit_review(LEADER_TASK_ID_OF_FIXTURE, approve())

    assert receipt.to_wire() == load("review-receipt.approve.json")
    assert receipt.leader_task_status == "succeeded"
    assert lane.phase == "closed"


async def test_request_rework_reopens_the_round_and_names_the_new_tasks() -> None:
    lane = port()
    await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    lane.worker_tasks_finished()

    receipt = await lane.submit_review(LEADER_TASK_ID_OF_FIXTURE, rework())

    assert receipt.verdict == "request_rework"
    assert receipt.leader_task_status == "in_progress"
    assert len(receipt.rework_task_ids) == 1
    # Back to executing, and — frozen invariant 1 — without the round's evidence,
    # because the next verdict must rest on the next round's.
    assert lane.phase == "executing"
    assert (await lane.fetch_assignment(LEADER_TASK_ID_OF_FIXTURE)).review_evidence is None


async def test_a_replayed_plan_returns_the_original_receipt() -> None:
    """Frozen invariant 2. The Bridge never retries, so this is what makes an
    ambiguous failure recoverable at all."""

    lane = port()
    first = await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    second = await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    assert second == first


async def test_a_replayed_verdict_returns_the_original_receipt() -> None:
    lane = port()
    await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    lane.worker_tasks_finished()
    first = await lane.submit_review(LEADER_TASK_ID_OF_FIXTURE, approve())
    assert await lane.submit_review(LEADER_TASK_ID_OF_FIXTURE, approve()) == first


async def test_a_different_plan_under_the_same_key_is_a_conflict_not_a_replacement() -> None:
    lane = port()
    await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())

    document = load("plan-decision.valid.json")
    document["engineeringSpec"]["summary"] = "a different plan entirely"
    with pytest.raises(LeaderActionRefused) as refusal:
        await lane.submit_plan(
            LEADER_TASK_ID_OF_FIXTURE, RepositoryPlanDecision.from_wire(document)
        )
    assert refusal.value.code == "phase_conflict"


async def test_reviewing_before_the_evidence_exists_is_a_phase_conflict() -> None:
    lane = port()
    await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    with pytest.raises(LeaderActionRefused) as refusal:
        await lane.submit_review(LEADER_TASK_ID_OF_FIXTURE, approve())
    assert refusal.value.code == "phase_conflict"


async def test_an_identical_replay_is_honoured_even_after_the_round_moved_on() -> None:
    """Where the two frozen rules meet, idempotency wins — and it has to.

    The README says a plan may only be submitted while planning, and that an
    identical resubmission returns the original receipt. Read the other way
    round the second rule could never fire: an accepted plan leaves the round in
    ``executing``, so the very replay the invariant exists for would be the one
    thing refused. A Bridge that never retries depends on this being the
    resolution — it is what makes "tell the leader it failed and let it ask
    again" a safe recovery rather than a way to plan twice.
    """

    lane = port()
    first = await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    lane.worker_tasks_finished()

    assert await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan()) == first
    assert lane.phase == "review_due", "a replay reports; it does not rewind the round"


async def test_another_leaders_task_id_is_not_found() -> None:
    lane = port()
    with pytest.raises(LeaderActionRefused) as refusal:
        await lane.fetch_assignment(uuid4())
    assert refusal.value.code == "assignment_not_found"


@pytest.mark.parametrize(
    "code",
    [
        "plan_invalid_assignee",
        "plan_invalid_allowed_paths",
        "plan_invalid_tests_removed",
    ],
)
async def test_an_out_of_bounds_plan_is_refused_with_the_frozen_code(code: str) -> None:
    """The envelope clamp's three refusals, each arriving as a typed exception
    carrying the code a real server would have named."""

    document = load("plan-decision.valid.json")
    if code == "plan_invalid_assignee":
        document["workerTasks"][0]["assigneeWorkerAgentId"] = str(uuid4())
    elif code == "plan_invalid_allowed_paths":
        document["workerTasks"][0]["allowedPaths"] = ["src/billing/"]
    else:
        document["workerTasks"][0]["tests"] = []

    with pytest.raises(LeaderActionRefused) as refusal:
        await port().submit_plan(
            LEADER_TASK_ID_OF_FIXTURE, RepositoryPlanDecision.from_wire(document)
        )
    assert refusal.value.code == code


async def test_a_verdict_about_work_the_leader_was_not_shown_is_refused() -> None:
    document = load("review-decision.request-rework.json")
    document["findings"][0]["workerTaskId"] = str(uuid4())
    lane = port()
    await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    lane.worker_tasks_finished()

    with pytest.raises(LeaderActionRefused) as refusal:
        await lane.submit_review(
            LEADER_TASK_ID_OF_FIXTURE, RepositoryReviewDecision.from_wire(document)
        )
    assert refusal.value.code == "review_invalid_findings"


@pytest.mark.parametrize("code", ["invalid_token", "forbidden_role", "decomposition_mode_conflict"])
async def test_a_deployment_refusal_reaches_the_lane_with_its_code(code: str) -> None:
    """The refusals no double can derive: they arrive scripted, and they arrive
    typed, so a lane that branches on the code is exercised against every one."""

    lane = port()
    lane.refusals.append(LeaderActionRefused("RepoMesh said no", code=code))
    with pytest.raises(LeaderActionRefused) as refusal:
        await lane.fetch_assignment(LEADER_TASK_ID_OF_FIXTURE)
    assert refusal.value.code == code


LEADER_TASK_ID_OF_FIXTURE = UUID(load("assignment-package.planning.json")["leaderTaskId"])


# ---------------------------------------------------------------------------
# The HTTP adapter, against the production route in process
# ---------------------------------------------------------------------------


def adapter(app: object, token: str) -> RepoMeshLeaderActionAdapter:
    return RepoMeshLeaderActionAdapter(
        endpoint="http://leader-actions.test",
        credential=lambda: token,
        transport=httpx.ASGITransport(app=app),  # type: ignore[arg-type]
    )


async def test_the_adapter_reads_a_real_assignment_package(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """One GET against the production FastAPI route, parsed by the production
    reader. Neither side is a copy of the other; the freeze is what they share."""

    client = build_client(monkeypatch)
    package = await adapter(client.app, LEADER_TOKEN).fetch_assignment(LEADER_TASK_ID)

    assert package.leader_task_id == LEADER_TASK_ID
    assert package.phase == "planning"
    assert package.review_evidence is None
    validate_document(schema("repository-assignment-package.schema.json"), package.to_wire())


@pytest.mark.parametrize(
    ("token", "task_id_is_known", "code"),
    [
        ("not-a-real-token", True, "invalid_token"),
        (WORKER_TOKEN, True, "forbidden_role"),
        (LEADER_TOKEN, False, "assignment_not_found"),
    ],
)
async def test_a_refused_read_arrives_as_a_typed_exception_with_the_frozen_code(
    monkeypatch: pytest.MonkeyPatch, token: str, task_id_is_known: bool, code: str
) -> None:
    client = build_client(monkeypatch)
    task_id = LEADER_TASK_ID if task_id_is_known else uuid4()

    with pytest.raises(LeaderActionRefused) as refusal:
        await adapter(client.app, token).fetch_assignment(task_id)

    assert refusal.value.code == code
    assert str(refusal.value)  # the server's own sentence, carried through


async def test_a_forged_leader_task_is_refused_as_not_the_assignee(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """AC-02's server half, seen from the consumer: naming somebody else's task
    is a 403 rather than a successful read, because the token names the caller
    and the path does not."""

    from api.test_leader_actions import LEADER_ID, OTHER_LEADER_TOKEN

    client = build_client(monkeypatch, assignee_agent_id=LEADER_ID)
    with pytest.raises(LeaderActionRefused) as refusal:
        await adapter(client.app, OTHER_LEADER_TOKEN).fetch_assignment(LEADER_TASK_ID)
    assert refusal.value.code == "forbidden_not_assignee"


@pytest.mark.parametrize("status", [429, 500, 503])
async def test_a_control_plane_that_did_not_decide_is_unavailable(status: int) -> None:
    async def answer(request: httpx.Request) -> httpx.Response:
        return httpx.Response(status, json={"detail": "busy"})

    with pytest.raises(LeaderActionUnavailable):
        await adapter_over(answer).fetch_assignment(LEADER_TASK_ID)


async def test_a_control_plane_that_cannot_be_reached_is_unavailable() -> None:
    async def answer(request: httpx.Request) -> httpx.Response:
        raise httpx.ConnectError("no route to host")

    with pytest.raises(LeaderActionUnavailable):
        await adapter_over(answer).fetch_assignment(LEADER_TASK_ID)


async def test_a_two_hundred_that_is_not_the_document_is_a_refusal() -> None:
    """A receipt this process cannot read is not a receipt, and no retry makes
    it one — the same call the governed adapter makes."""

    async def answer(request: httpx.Request) -> httpx.Response:
        return httpx.Response(200, json={"schemaVersion": "something.else"})

    with pytest.raises(LeaderActionRefused, match="assignment package"):
        await adapter_over(answer).fetch_assignment(LEADER_TASK_ID)


async def test_the_adapter_makes_exactly_one_attempt_and_never_retries() -> None:
    """The writes are idempotent at the server, which is what makes a replay
    safe; deciding to replay is RepoMesh's judgement and not this adapter's."""

    attempts: list[str] = []

    async def answer(request: httpx.Request) -> httpx.Response:
        attempts.append(str(request.url))
        raise httpx.ConnectError("down")

    with pytest.raises(LeaderActionUnavailable):
        await adapter_over(answer).submit_plan(LEADER_TASK_ID, valid_plan())
    assert len(attempts) == 1


async def test_the_three_calls_use_the_frozen_paths_and_carry_the_member_token() -> None:
    seen: list[tuple[str, str, str]] = []

    async def answer(request: httpx.Request) -> httpx.Response:
        seen.append(
            (request.method, request.url.path, request.headers.get("Authorization", ""))
        )
        if request.method == "GET":
            return httpx.Response(200, json=load("assignment-package.planning.json"))
        if request.url.path.endswith("/plan"):
            return httpx.Response(200, json=load("plan-receipt.json"))
        return httpx.Response(200, json=load("review-receipt.approve.json"))

    lane = adapter_over(answer)
    await lane.fetch_assignment(LEADER_TASK_ID_OF_FIXTURE)
    await lane.submit_plan(LEADER_TASK_ID_OF_FIXTURE, valid_plan())
    await lane.submit_review(LEADER_TASK_ID_OF_FIXTURE, approve())

    assert seen == [
        ("GET", ASSIGNMENT_PATH.format(task_id=LEADER_TASK_ID_OF_FIXTURE), "Bearer member-token"),
        ("POST", PLAN_PATH.format(task_id=LEADER_TASK_ID_OF_FIXTURE), "Bearer member-token"),
        ("POST", REVIEW_PATH.format(task_id=LEADER_TASK_ID_OF_FIXTURE), "Bearer member-token"),
    ]


async def test_closing_an_adapter_that_never_called_anything_is_safe() -> None:
    """The adapter holds a process-lifetime pool, so it owes a way to give it
    back — the same obligation the governed adapter carries, and it must not
    depend on a call having been made or on being closed only once."""

    resolutions = 0

    def credential() -> str:
        nonlocal resolutions
        resolutions += 1
        return "member-token"

    calls: list[str] = []

    async def answer(request: httpx.Request) -> httpx.Response:
        calls.append(str(request.url))
        return httpx.Response(200, json=load("assignment-package.planning.json"))

    lane = RepoMeshLeaderActionAdapter(
        endpoint="http://leader-actions.test",
        credential=credential,
        transport=httpx.MockTransport(answer),
    )

    await lane.close()
    await lane.close()

    assert calls == []
    assert resolutions == 0, "nothing resolved a secret it never needed"


def adapter_over(handler) -> RepoMeshLeaderActionAdapter:
    return RepoMeshLeaderActionAdapter(
        endpoint="http://leader-actions.test",
        credential=lambda: "member-token",
        transport=httpx.MockTransport(handler),
    )


# ---------------------------------------------------------------------------
# The coordination session (adjudication D-8)
# ---------------------------------------------------------------------------

SESSION_THREAD = "019fc762-d677-7cd3-80e6-cd25db68a7a7"


def succeeded(summary: str, *, thread: str | None = SESSION_THREAD) -> DriverResult:
    return DriverResult(
        status=DriverResultStatus.SUCCEEDED,
        summary=summary,
        native_session_id=thread,
    )


async def coordination(tmp_path, result: DriverResult) -> tuple[LeaderCoordinationSession, Any]:
    """A leader session over a fake driver, past its startup gate.

    Built through the conversation lane's own helper, because that is the claim:
    there is one session stack and the leader reads a different answer out of it
    (adjudication B2-1). A second builder here would be a second stack.
    """

    driver = _FakeDriver(result)
    session, _ = _make_session(tmp_path, driver)
    await session.ensure_ready()
    return LeaderCoordinationSession(session), driver


def plan_answer() -> str:
    document = load("plan-decision.valid.json")
    del document["schemaVersion"]
    del document["provenance"]
    return json.dumps(document)


def review_answer() -> str:
    document = load("review-decision.approve.json")
    del document["schemaVersion"]
    del document["provenance"]
    return json.dumps(document)


async def test_a_coordination_session_turns_facts_into_a_plan(tmp_path) -> None:
    session, _ = await coordination(tmp_path, succeeded(plan_answer()))

    decision = await session.plan(planning_package())

    assert decision.provenance.source == "leader-codex-session"
    assert decision.provenance.session_thread_id == SESSION_THREAD
    assert [task.node_id for task in decision.worker_tasks] == ["contract", "rounding"]
    validate_document(schema("repository-plan-decision.schema.json"), decision.to_wire())


async def test_a_coordination_session_turns_evidence_into_a_verdict(tmp_path) -> None:
    package = RepositoryAssignmentPackage.from_wire(load("assignment-package.review-due.json"))
    session, _ = await coordination(tmp_path, succeeded(review_answer()))

    decision = await session.review(package)

    assert decision.verdict == "approve"
    assert decision.provenance.session_thread_id == SESSION_THREAD
    validate_document(schema("repository-review-decision.schema.json"), decision.to_wire())


async def test_a_fenced_answer_is_unwrapped_but_never_repaired(tmp_path) -> None:
    session, _ = await coordination(
        tmp_path, succeeded(f"Here is the plan:\n\n```json\n{plan_answer()}\n```\n")
    )
    assert (await session.plan(planning_package())).worker_tasks


async def test_the_leader_session_is_given_no_repository(tmp_path) -> None:
    """Adjudication D-8's second layer, asserted three ways.

    The prompt names no path on this machine; the process is started in the
    Bridge's own scratch directory rather than any checkout; and that directory
    holds nothing. The first is the one that matters most, because a fact
    package is the only thing about this lane that a future change could
    accidentally widen.
    """

    session, driver = await coordination(tmp_path, succeeded(plan_answer()))
    package = planning_package()

    await session.plan(package)

    request = driver.requests[0]
    prompt = request.prompt
    # Nothing from this machine is in the prompt: not the workspace, not the
    # session root, not the temp directory, not a drive letter.
    assert str(tmp_path) not in prompt
    assert str(request.workspace) not in prompt
    assert "\\" not in prompt and ":\\" not in prompt
    # And the working directory is not a repository: it is an empty scratch dir
    # the Bridge owns, with no checkout under it.
    assert request.workspace.is_dir()
    assert list(request.workspace.iterdir()) == []
    assert not (request.workspace / ".git").exists()
    # Nothing resumes: each decision is its own thread, so a verdict cannot lean
    # on remembering the plan instead of on the evidence.
    assert request.resume_session_id is None


def test_the_rendered_fact_package_carries_only_contract_data() -> None:
    """The same claim as a property of the renderer, without a session at all."""

    rendered = render_fact_package(
        RepositoryAssignmentPackage.from_wire(load("assignment-package.review-due.json"))
    )
    # Everything a leader needs to plan and review is present...
    assert "pricing-codex-worker" in rendered
    assert "src/pricing_core/" in rendered
    assert "python scripts/run_tests.py" in rendered
    assert "3f2a9d1b7c4e8f0a6b5d2c1e9f8a7b6c5d4e3f2a" in rendered
    # ...and the hints are labelled as hints rather than as requirements.
    assert "Not authoritative" in rendered
    # ...but nothing that could be a location on a machine.
    assert "\\" not in rendered
    assert "/home/" not in rendered and "C:" not in rendered


@pytest.mark.parametrize(
    "render", [render_plan_instructions, render_review_instructions]
)
def test_both_prompts_tell_the_session_it_has_no_repository(render) -> None:
    package = RepositoryAssignmentPackage.from_wire(load("assignment-package.review-due.json"))
    assert "no repository" in render(package)


@pytest.mark.parametrize(
    ("answer", "expected"),
    [
        ("I think we should split this into two tasks.", "not JSON"),
        ("", "empty"),
        ('{"engineeringSpec": {"summary": "x"}}', "missing required"),
        ('["not", "an", "object"]', "not a JSON object"),
    ],
)
async def test_a_malformed_plan_is_refused_and_says_why(tmp_path, answer, expected) -> None:
    """Adjudication B2-2: refuse and narrate, never quietly repair and never
    lean on the server's clamp to catch it."""

    session, _ = await coordination(tmp_path, succeeded(answer))
    with pytest.raises(LeaderDocumentInvalid, match=expected):
        await session.plan(planning_package())


async def test_two_fenced_blocks_are_ambiguous_rather_than_first_wins(tmp_path) -> None:
    session, _ = await coordination(
        tmp_path, succeeded(f"```json\n{plan_answer()}\n```\nor maybe\n```json\n{{}}\n```")
    )
    with pytest.raises(LeaderDocumentInvalid, match="ambiguous"):
        await session.plan(planning_package())


async def test_a_session_that_writes_its_own_provenance_is_refused(tmp_path) -> None:
    """Frozen invariant 5: the one claim the model is not in a position to make.

    Overwriting it silently would leave the field meaningless and this refusal
    untested, which is exactly how a plan with borrowed provenance would reach
    the server looking honest.
    """

    document = load("plan-decision.valid.json")
    del document["schemaVersion"]
    session, _ = await coordination(tmp_path, succeeded(json.dumps(document)))

    with pytest.raises(LeaderDocumentInvalid, match="not in a position"):
        await session.plan(planning_package())


async def test_a_session_that_announced_no_thread_cannot_claim_provenance(tmp_path) -> None:
    session, _ = await coordination(tmp_path, succeeded(plan_answer(), thread=None))
    with pytest.raises(LeaderDocumentInvalid, match="provenance"):
        await session.plan(planning_package())


@pytest.mark.parametrize(
    "status",
    [DriverResultStatus.FAILED, DriverResultStatus.TIMEOUT, DriverResultStatus.INTERRUPTED],
)
async def test_a_turn_that_did_not_deliver_produces_no_decision(tmp_path, status) -> None:
    session, _ = await coordination(
        tmp_path,
        DriverResult(status=status, summary="", native_session_id=SESSION_THREAD),
    )
    with pytest.raises(LeaderDocumentInvalid, match="did not produce"):
        await session.plan(planning_package())


async def test_a_plan_outside_the_envelope_never_leaves_the_bridge(tmp_path) -> None:
    """The session's own output is clamped here, before any POST exists."""

    document = load("plan-decision.valid.json")
    del document["schemaVersion"]
    del document["provenance"]
    document["workerTasks"][0]["assigneeWorkerAgentId"] = str(uuid4())
    session, _ = await coordination(tmp_path, succeeded(json.dumps(document)))

    with pytest.raises(LeaderDocumentInvalid, match="outside its bounds"):
        await session.plan(planning_package())
