from typing import Protocol
from uuid import UUID

from repomesh.modules.agent_runtime.domain import CodingRun, SessionBinding, Workspace


class CodingRunStore(Protocol):
    async def add(self, run: CodingRun) -> None: ...
    async def prepare(
        self,
        run: CodingRun,
        workspace: Workspace,
        *,
        expected_workspace_revision: int,
    ) -> None: ...
    async def get(self, run_id: UUID) -> CodingRun | None: ...
    async def update(self, run: CodingRun, *, expected_revision: int) -> None: ...


class WorkspaceStore(Protocol):
    async def add(self, workspace: Workspace) -> None: ...
    async def get(self, workspace_id: UUID) -> Workspace | None: ...
    async def update(self, workspace: Workspace, *, expected_revision: int) -> None: ...


class SessionBindingStore(Protocol):
    async def add(self, binding: SessionBinding) -> None: ...
    async def get_by_run(self, run_id: UUID) -> SessionBinding | None: ...
