import hashlib
import json

from repomesh.modules.agent_directory.contracts import AgentPrincipalReader, AgentRole
from repomesh.modules.identity_access.contracts import (
    AgentAuthorizationGateway,
    AuthorizationAction,
    AuthorizationRequest,
)
from repomesh.modules.project.contracts import ProjectTopologyReader
from repomesh.modules.specification.contracts import (
    BuildCodingAgentPackageCommand,
    CodingAgentPackage,
    RenderedSpecification,
    SpecificationKind,
    SpecificationStatus,
)
from repomesh.modules.specification.domain import (
    Specification,
    SpecificationConflict,
    SpecificationDenied,
    SpecificationNotFound,
)
from repomesh.modules.specification.ports import SpecificationStore
from repomesh.modules.task_orchestration.contracts import TaskReader


def _sha256(value: str) -> str:
    return f"sha256:{hashlib.sha256(value.encode()).hexdigest()}"


def _section(title: str, values: tuple[str, ...]) -> list[str]:
    if not values:
        return []
    return [f"## {title}", "", *(f"- {value}" for value in values), ""]


class SpecificationRenderer:
    """Render a database specification as a deterministic, read-only agent view."""

    def render_task(self, specification: Specification) -> RenderedSpecification:
        if specification.kind is not SpecificationKind.TASK:
            raise ValueError("task renderer requires a task specification")
        version = specification.current_version
        content = version.content
        lines = [
            f"# {specification.title}",
            "",
            "> This file is generated by RepoMesh. Do not edit it directly.",
            "",
            "## Metadata",
            "",
            f"- Spec ID: `{specification.id}`",
            f"- Version: `{version.version}`",
            f"- Status: `{specification.status.value}`",
            f"- Source hash: `{version.content_hash}`",
            f"- Task ID: `{specification.task_id}`",
            f"- Repository ID: `{specification.repository_id}`",
            "",
            "## Current task",
            "",
            content.goal,
            "",
            *_section("Acceptance criteria", content.acceptance),
            *_section("Scope", content.scope),
            *_section("Constraints", content.constraints),
            *_section("Required dependencies", content.dependencies),
            *_section("Interface requirements", content.interface_changes),
            *_section("Allowed paths", content.allowed_paths),
            *_section("Forbidden paths", content.forbidden_paths),
            *_section("Required tests", content.tests),
        ]
        rendered = "\n".join(lines).rstrip() + "\n"
        return RenderedSpecification(
            specification_id=specification.id,
            version_id=version.id,
            version=version.version,
            source_content_hash=version.content_hash,
            rendered_content_hash=_sha256(rendered),
            mount_path=".repomesh/context/current-task.md",
            mime_type="text/markdown",
            content=rendered,
        )


class BuildCodingAgentPackage:
    def __init__(
        self,
        directory: AgentPrincipalReader,
        topologies: ProjectTopologyReader,
        tasks: TaskReader,
        specifications: SpecificationStore,
        authorizer: AgentAuthorizationGateway,
        renderer: SpecificationRenderer | None = None,
    ) -> None:
        self._directory = directory
        self._topologies = topologies
        self._tasks = tasks
        self._specifications = specifications
        self._authorizer = authorizer
        self._renderer = renderer or SpecificationRenderer()

    async def execute(
        self, command: BuildCodingAgentPackageCommand
    ) -> CodingAgentPackage:
        worker = await self._directory.get_view(command.worker_agent_id)
        if worker is None or worker.role is not AgentRole.WORKER:
            raise SpecificationDenied("coding package requires a worker agent")
        task = await self._tasks.get_view(command.task_id)
        if task is None:
            raise SpecificationNotFound(f"task not found: {command.task_id}")
        if (
            task.organization_id != command.organization_id
            or task.project_id != command.project_id
            or task.repository_id != command.repository_id
            or task.assignee_agent_id != command.worker_agent_id
        ):
            raise SpecificationDenied("worker is not assigned to this task")
        topology = await self._topologies.get_view(command.project_id)
        decision = self._authorizer.authorize(
            worker,
            AuthorizationRequest(
                action=AuthorizationAction.CODING_EXECUTE,
                organization_id=command.organization_id,
                project_id=command.project_id,
                repository_id=command.repository_id,
            ),
            topology=topology,
        )
        if not decision.allowed:
            raise SpecificationDenied(decision.reason)

        candidates = tuple(
            specification
            for specification in await self._specifications.list_by_project(
                command.project_id
            )
            if specification.kind is SpecificationKind.TASK
            and specification.task_id == command.task_id
            and specification.repository_id == command.repository_id
            and specification.status
            in {SpecificationStatus.APPROVED, SpecificationStatus.FROZEN}
        )
        if not candidates:
            raise SpecificationNotFound("approved task specification not found")
        if len(candidates) > 1:
            raise SpecificationConflict("multiple approved task specifications found")

        specification = candidates[0]
        content = specification.current_version.content
        rendered = self._renderer.render_task(specification)
        payload = {
            "project_id": str(command.project_id),
            "repository_id": str(command.repository_id),
            "task_id": str(command.task_id),
            "worker_agent_id": str(command.worker_agent_id),
            "instruction": content.goal,
            "acceptance": list(content.acceptance),
            "constraints": list(content.constraints),
            "dependencies": list(content.dependencies),
            "interface_changes": list(content.interface_changes),
            "allowed_paths": list(content.allowed_paths),
            "forbidden_paths": list(content.forbidden_paths),
            "test_commands": list(content.tests),
            "context_files": [
                {
                    "specification_id": str(rendered.specification_id),
                    "version_id": str(rendered.version_id),
                    "source_content_hash": rendered.source_content_hash,
                    "rendered_content_hash": rendered.rendered_content_hash,
                    "mount_path": rendered.mount_path,
                }
            ],
        }
        encoded = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        return CodingAgentPackage(
            project_id=command.project_id,
            repository_id=command.repository_id,
            task_id=command.task_id,
            worker_agent_id=command.worker_agent_id,
            instruction=content.goal,
            acceptance=content.acceptance,
            constraints=content.constraints,
            dependencies=content.dependencies,
            interface_changes=content.interface_changes,
            allowed_paths=content.allowed_paths,
            forbidden_paths=content.forbidden_paths,
            test_commands=content.tests,
            context_files=(rendered,),
            content_hash=_sha256(encoded),
        )
