import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from uuid import UUID

from repomesh.shared.domain import new_id


def tokenize(text: str) -> frozenset[str]:
    return frozenset(token.lower() for token in re.findall(r"[\w-]+", text, re.UNICODE))


@dataclass(frozen=True, slots=True)
class AutoCard:
    """Automatic snapshot of a repository, generated by ``scan.py``.

    This is the primary signal for LLM-based discovery.  Every field is optional
    so that scanners can incrementally populate it; an empty card is valid but
    will be flagged ``low_signal``.
    """

    top_dirs: tuple[str, ...] = ()
    deps: tuple[str, ...] = ()
    recent_commits: tuple[str, ...] = ()
    exposed_apis: tuple[str, ...] = ()
    low_signal: bool = False


@dataclass(frozen=True, slots=True)
class RepositoryProfile:
    name: str
    url: str
    description: str = ""
    topics: 