#!/usr/bin/env bash
# Baseline scenes 28 (alert drill F) and 30 (final ledger). Run last.
source "$(dirname "$0")/probe_lib.sh"
export SC="$(cd "$(dirname "$0")" && pwd)"
export TEAM=repomesh-team-dfb8a4cda6f74ee795e4197963151308
export TEAM_TA=repomesh-team-22c4d38e465c42c8b93b20ae97cc250d

cp "$SC/drill_issue.json" "$OUT/28.request.json"
probe 28 'echo "## 1. create a rule that must fire (calls > 0 over 1440 min)"; R=$(curl -sS -X POST -H "Authorization: Bearer $T" -H "Content-Type: application/json" $API/observe/alert-rules -d "{\"name\":\"baseline drill F: calls>0\",\"metric\":\"calls\",\"operator\":\"gt\",\"threshold\":0,\"window_minutes\":1440,\"enabled\":true}"); echo "$R"; RID=$(printf "%s" "$R" | python -c "import json,sys; print(json.load(sys.stdin)[\"id\"])"); echo "rule_id=$RID"; echo "## 2. evaluate now"; curl -sS -X POST -H "Authorization: Bearer $T" $API/observe/alerts/evaluate | head -c 600; echo; echo "## 3. operations status while firing"; curl -sS -H "Authorization: Bearer $T" $API/observe/operations/status | head -c 300; echo; echo "## 4. is the alert action configured in the api container?"; docker exec goai-infra-repomesh-api-1 sh -c "env | grep -c ^REPOMESH_OPERATIONS_ALERT_ACTION= || echo REPOMESH_OPERATIONS_ALERT_ACTION unset - settings default none"; echo "## 5. POST /issues while the alert is firing (script expects 503 intake_paused)"; curl -sS -o "$OUT/28.post.json" -w "http %{http_code}\n" -X POST -H "Authorization: Bearer $T" -H "Content-Type: application/json" $API/issues --data-binary @"$OUT/28.request.json"; head -c 300 "$OUT/28.post.json"; echo; echo "## 6. cleanup: delete the drill rule (its events cascade)"; curl -sS -o /dev/null -w "delete http %{http_code}\n" -X DELETE -H "Authorization: Bearer $T" $API/observe/alert-rules/$RID; echo -n "active alerts after cleanup: "; curl -sS -H "Authorization: Bearer $T" $API/observe/alerts/active; echo; curl -sS -H "Authorization: Bearer $T" $API/observe/operations/status | head -c 120; echo'

probe 30 'echo "## RepoMesh ledger"; $PSQL -c "select '"'"'task_orchestration.tasks'"'"', count(*) from task_orchestration.tasks union all select '"'"'task_orchestration.task_assignment_attempts'"'"', count(*) from task_orchestration.task_assignment_attempts union all select '"'"'task_orchestration.execution_plans'"'"', count(*) from task_orchestration.execution_plans union all select '"'"'agent_runtime.runner_dispatches'"'"', count(*) from agent_runtime.runner_dispatches union all select '"'"'agent_runtime.runner_events'"'"', count(*) from agent_runtime.runner_events union all select '"'"'agent_runtime.worker_execution_reservations'"'"', count(*) from agent_runtime.worker_execution_reservations union all select '"'"'delivery.change_sets'"'"', count(*) from delivery.change_sets union all select '"'"'delivery.scm_commands'"'"', count(*) from delivery.scm_commands union all select '"'"'review_validation.validation_snapshots'"'"', count(*) from review_validation.validation_snapshots union all select '"'"'repository_intelligence.plan_snapshots'"'"', count(*) from repository_intelligence.plan_snapshots union all select '"'"'observability.alert_rules'"'"', count(*) from observability.alert_rules union all select '"'"'observability.alert_events'"'"', count(*) from observability.alert_events"; echo "## tasks by status"; $PSQL -c "select status, count(*) from task_orchestration.tasks group by 1 order by 1"; echo "## dispatch"; $PSQL -c "select run_id, status, lease_until, task_payload->>'"'"'adapterId'"'"' from agent_runtime.runner_dispatches"; echo "## reservation"; $PSQL -c "select id, status, lease_expires_at from agent_runtime.worker_execution_reservations"; echo "## shared-drive task objects (recursive)"; docker exec agentteams-controller mc ls -r agentteams/agentteams-storage/teams/ | grep "/tasks/" | grep -v "\.keep$"; echo "## forbidden content in task dirs (.git, node_modules, __pycache__)"; docker exec agentteams-controller mc ls -r agentteams/agentteams-storage/teams/ | grep "/tasks/" | grep -c -E "/\.git/|node_modules|__pycache__" || true; echo "## content hash of the task-object listing (names+sizes)"; docker exec agentteams-controller mc ls -r agentteams/agentteams-storage/teams/ | grep "/tasks/" | awk "{print \$4, \$6}" | sort | sha256sum'
