from repomesh.modules.agent_runtime.ports.agent_adapter import (
    PermissionMode,
    PromptDelivery,
)

from .base import AdapterSpec, AuthProbeSpec, CliAgentAdapter, PromptStyle

CLAUDE_PERMISSIONS = {
    PermissionMode.ACCEPT_EDITS: ("--permission-mode", "acceptEdits"),
    PermissionMode.AUTO: ("--permission-mode", "auto"),
    PermissionMode.BYPASS_PERMISSIONS: ("--permission-mode", "bypassPermissions"),
}
CODEX_PERMISSIONS = {
    PermissionMode.ACCEPT_EDITS: ("--ask-for-approval", "on-request"),
    PermissionMode.AUTO: (
        "--ask-for-approval",
        "on-request",
        "-c",
        'approvals_reviewer="auto_review"',
    ),
    PermissionMode.BYPASS_PERMISSIONS: ("--dangerously-bypass-approvals-and-sandbox",),
}
CURSOR_PERMISSIONS = {
    PermissionMode.AUTO: ("--force",),
    PermissionMode.BYPASS_PERMISSIONS: ("--yolo",),
}


SPECS = (
    AdapterSpec(
        id="claude-code",
        display_name="Claude Code",
        binaries=("claude",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        launch_prefix=("--print", "--output-format", "stream-json", "--verbose"),
        prompt_style=PromptStyle.POSITIONAL,
        session_flag="--session-id",
        model_flag="--model",
        system_prompt_flag="--append-system-prompt",
        allowed_tools_flag="--allowedTools",
        disallowed_tools_flag="--disallowedTools",
        permission_arguments=CLAUDE_PERMISSIONS,
        auth=AuthProbeSpec(("auth", "status"), ("ANTHROPIC_API_KEY",)),
        auth_timeout_seconds=10.0,
        restore_prefix=("--print", "--output-format", "stream-json", "--verbose"),
        restore_flag="--resume",
        restore_accepts_prompt=True,
    ),
    AdapterSpec(
        id="codex",
        display_name="OpenAI Codex",
        binaries=("codex",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        model_flag="--model",
        permission_arguments=CODEX_PERMISSIONS,
        auth=AuthProbeSpec(("login", "status"), ("OPENAI_API_KEY",)),
        restore_prefix=("resume",),
        restore_flag="",
    ),
    AdapterSpec(
        id="opencode",
        display_name="OpenCode",
        binaries=("opencode",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        prompt_style=PromptStyle.FLAG,
        prompt_flag="--prompt",
        model_flag="--model",
        auth=AuthProbeSpec(environment_variables=("OPENAI_API_KEY", "ANTHROPIC_API_KEY")),
        restore_flag="--session",
    ),
    AdapterSpec(
        id="grok",
        display_name="Grok CLI",
        binaries=("grok",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        launch_prefix=("--no-auto-update",),
        system_prompt_flag="--rules",
        auth=AuthProbeSpec(environment_variables=("GROK_API_KEY", "XAI_API_KEY")),
        restore_prefix=("--no-auto-update",),
        restore_flag="-r",
    ),
    AdapterSpec(
        id="cursor",
        display_name="Cursor Agent",
        binaries=("cursor-agent",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        permission_arguments=CURSOR_PERMISSIONS,
        auth=AuthProbeSpec(("status",)),
        restore_flag="--resume",
    ),
    AdapterSpec(
        id="qwen",
        display_name="Qwen Code",
        binaries=("qwen",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        prompt_style=PromptStyle.FLAG,
        prompt_flag="-i",
        model_flag="--model",
        system_prompt_flag="--append-system-prompt",
        auth=AuthProbeSpec(
            environment_variables=("QWEN_API_KEY", "DASHSCOPE_API_KEY", "OPENAI_API_KEY")
        ),
        restore_flag="--resume",
    ),
    AdapterSpec(
        id="copilot",
        display_name="GitHub Copilot CLI",
        binaries=("copilot",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        prompt_style=PromptStyle.FLAG,
        prompt_flag="--interactive",
        model_flag="--model",
        auth=AuthProbeSpec(environment_variables=("GH_TOKEN", "GITHUB_TOKEN")),
        restore_flag="--resume",
    ),
    AdapterSpec(
        id="kimi",
        display_name="Kimi Code",
        binaries=("kimi",),
        prompt_delivery=PromptDelivery.AFTER_START,
        prompt_style=PromptStyle.NONE,
        auth=AuthProbeSpec(environment_variables=("KIMI_API_KEY", "MOONSHOT_API_KEY")),
        restore_flag="--session",
    ),
    AdapterSpec(
        id="droid",
        display_name="Factory Droid",
        binaries=("droid",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        prompt_style=PromptStyle.POSITIONAL,
        model_flag="--model",
        system_prompt_flag="--append-system-prompt",
        system_prompt_file_flag="--append-system-prompt-file",
        auth=AuthProbeSpec(environment_variables=("FACTORY_API_KEY",)),
        restore_flag="-r",
    ),
    AdapterSpec(
        id="amp",
        display_name="Amp",
        binaries=("amp",),
        prompt_delivery=PromptDelivery.AFTER_START,
        prompt_style=PromptStyle.NONE,
        auth=AuthProbeSpec(("usage", "--no-color"), ("AMP_API_KEY",)),
        restore_flag="--resume",
    ),
    AdapterSpec(
        id="agy",
        display_name="Agy",
        binaries=("agy",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        prompt_style=PromptStyle.FLAG,
        prompt_flag="--prompt-interactive",
        workspace_flag="--add-dir",
        model_flag="--model",
        restore_flag="--conversation",
    ),
    AdapterSpec(
        id="crush",
        display_name="Crush",
        binaries=("crush",),
        prompt_delivery=PromptDelivery.AFTER_START,
        prompt_style=PromptStyle.NONE,
        workspace_flag="--cwd",
        restore_flag="--session",
    ),
    AdapterSpec(
        id="aider",
        display_name="Aider",
        binaries=("aider",),
        prompt_delivery=PromptDelivery.AFTER_START,
        launch_prefix=("--no-check-update", "--no-stream", "--no-pretty"),
        prompt_style=PromptStyle.NONE,
        system_prompt_file_flag="--read",
        auth=AuthProbeSpec(
            environment_variables=(
                "OPENAI_API_KEY",
                "ANTHROPIC_API_KEY",
                "GEMINI_API_KEY",
                "GROQ_API_KEY",
            )
        ),
        restore_prefix=None,
        restore_flag=None,
    ),
    AdapterSpec(
        id="goose",
        display_name="Goose",
        binaries=("goose",),
        prompt_delivery=PromptDelivery.AFTER_START,
        launch_prefix=("run", "-t", "", "--interactive"),
        prompt_style=PromptStyle.NONE,
        model_flag="--model",
        system_prompt_flag="--system",
        auth=AuthProbeSpec(environment_variables=("GOOSE_API_KEY", "OPENAI_API_KEY")),
        restore_prefix=("run", "--resume"),
        restore_flag="--session-id",
    ),
    AdapterSpec(
        id="auggie",
        display_name="Auggie",
        binaries=("auggie",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        launch_prefix=("--print",),
        model_flag="--model",
        system_prompt_file_flag="--rules",
        auth=AuthProbeSpec(("account", "status")),
        restore_prefix=("--print",),
        restore_flag="--resume",
    ),
    AdapterSpec(
        id="continue",
        display_name="Continue CLI",
        binaries=("cn",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        auth=AuthProbeSpec(environment_variables=("CONTINUE_API_KEY",)),
        restore_flag="--fork",
    ),
    AdapterSpec(
        id="devin",
        display_name="Devin CLI",
        binaries=("devin",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        auth=AuthProbeSpec(("auth", "status"), ("DEVIN_API_KEY",)),
        restore_flag="-r",
    ),
    AdapterSpec(
        id="cline",
        display_name="Cline CLI",
        binaries=("cline",),
        prompt_delivery=PromptDelivery.AFTER_START,
        prompt_style=PromptStyle.NONE,
        system_prompt_flag="-s",
        restore_flag="--id",
    ),
    AdapterSpec(
        id="kiro",
        display_name="Kiro CLI",
        binaries=("kiro-cli",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        launch_prefix=("chat",),
        auth=AuthProbeSpec(("whoami",)),
        restore_prefix=("chat",),
        restore_flag="--resume-id",
    ),
    AdapterSpec(
        id="kilocode",
        display_name="Kilo Code",
        binaries=("kilocode",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        prompt_style=PromptStyle.FLAG,
        prompt_flag="--prompt",
        model_flag="--model",
        auth=AuthProbeSpec(("auth", "list")),
        restore_flag="--session",
    ),
    AdapterSpec(
        id="vibe",
        display_name="Mistral Vibe",
        binaries=("vibe",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        launch_prefix=("--trust",),
        workspace_flag="--workdir",
        auth=AuthProbeSpec(environment_variables=("MISTRAL_API_KEY",)),
        restore_prefix=("--trust",),
        restore_flag="--resume",
    ),
    AdapterSpec(
        id="pi",
        display_name="Pi Coding Agent",
        binaries=("pi",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        prompt_style=PromptStyle.POSITIONAL,
        model_flag="--model",
        system_prompt_flag="--append-system-prompt",
        restore_flag="--session",
    ),
    AdapterSpec(
        id="autohand",
        display_name="Autohand",
        binaries=("autohand",),
        prompt_delivery=PromptDelivery.IN_COMMAND,
        workspace_flag="--path",
        model_flag="--model",
        system_prompt_flag="--sys-prompt",
        restore_prefix=("resume",),
        restore_flag="",
    ),
)


def create_adapters() -> tuple[CliAgentAdapter, ...]:
    return tuple(CliAgentAdapter(spec) for spec in SPECS)
